version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply 
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  #run-ansible-playbook:
  #  #working_directory: /tmp/project
  #  docker:
  #    - image: 'tomonorimatsumura/centos7-ansible:yum'
  #  steps:
  #    - attach_workspace:
  #        at: .
  #    #- checkout
  #    - run:
  #        name: Install System Packages
  #        command: yum install -y python3
  #    - run:
  #        name: Upgrade pip
  #        command: pip install --upgrade pip
  #    - run:
  #        name: Uninstall Ansible
  #        command: pip uninstall --yes ansible
  #    - run:
  #        name: Install latest Ansible
  #        command: pip install ansible
  #    - run:
  #        name: Download requiered playbook modules
  #        command: ansible-galaxy collection install community.docker amazon.aws
  #    - run:
  #        name: Run Ansible Playbook
  #        command: ansible-playbook deploy-configs.yml -i inventory --user ec2-user --key-file $PRIVATE_KEY -e "@vars.yml"
  #    - persist_to_workspace:
  #        root: .
  #        paths:
  #          - .

  run-ansible-playbook:
    #working_directory: /tmp/project
    docker:
      - image: 'willhallonline/ansible'
    steps:
      - attach_workspace:
          at: .
      #- checkout
     #- run:
     #    name: Install System Packages
     #    command: yum install -y python3
     #- run:
     #    name: Upgrade pip
     #    command: pip install --upgrade pip
     #- run:
     #    name: Uninstall Ansible
     #    command: pip uninstall --yes ansible
     #- run:
     #    name: Install latest Ansible
     #    command: pip install ansible
     #- run:
          name: Download requiered playbook modules
          command: ansible-galaxy collection install community.docker amazon.aws
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook deploy-configs.yml -i inventory --user ec2-user --key-file $PRIVATE_KEY -e "@vars.yml"
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy 
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_deploy_webpagetest:
    jobs:
      - plan-apply
      - apply:
          requires:
            - plan-apply
      - run-ansible-playbook:
          requires:
            - apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy